// packages/sveltekit/src/lib/components/ChatMessage.svelte
<script lang="ts">
    import { createAgentAvatarUrl } from "@mecha-agent-inference-client/core/client";
    import IsTypingState from "./IsTypingState.svelte";

    type ChatMessageProps = {
        agent: Agent;
        isGenerating?: boolean;
    } & ChatMessage;

    const { role, agent, content, isGenerating }: ChatMessageProps = $props();

    const isUserPart = role === "user";
</script>

<div class={`chat-box ${isUserPart ? "chat-box-user" : ""}`}>
    {#if isUserPart}
        <span class="chat-avatar user-avatar"></span>
    {:else if agent.avatar}
        <img
            class="chat-avatar"
            src={createAgentAvatarUrl(agent.avatar)}
            alt="Agent Avatar"
        />
    {:else}
        <span class="chat-avatar agent-fallback-avatar"></span>
    {/if}
    <div class="chat-content">
        <span class={`chat-name ${isUserPart ? "chat-name-user" : ""}`}>
            {isUserPart ? "You" : agent.agentName}
        </span>
        <div
            class={`chat-message ${isUserPart ? "chat-message-user" : "chat-message-agent"}`}
        >
            {#if content}
                <p class="chat-text">{content}</p>
            {:else if isGenerating}
                <IsTypingState />
            {/if}
        </div>
    </div>
</div>

// packages/nextjs/src/components/ChatMessage.tsx
import Image from "next/image";
import IsTypingState from "./IsTypingState";
import { createAgentAvatarUrl } from "@mecha-agent-inference-client/core/client";

type ChatMessageProps = {
    agent: Agent;
    isGenerating?: boolean
} & ChatMessage

export default function ChatMessage({ agent, role, content, isGenerating }: ChatMessageProps) {
    const isUserPart = role === "user";

    return (
        <div className={`chat-box ${isUserPart ? "chat-box-user" : ""}`}>
            {
                isUserPart ? <span className="chat-avatar user-avatar" /> :
                    agent.avatar ?
                        <Image
                            width={40}
                            height={40}
                            className='chat-avatar'
                            src={createAgentAvatarUrl(agent.avatar)}
                            alt={"Agent Avatar"}
                        /> : <span className="chat-avatar agent-fallback-avatar" />
            }
            <div className="chat-content">
                <span className={`chat-name ${isUserPart ? "chat-name-user" : ""}`}>
                    {isUserPart ? "You" : agent.agentName}
                </span>
                <div className={`chat-message ${isUserPart ? "chat-message-user" : "chat-message-agent"}`}>
                    {content ? <p className="chat-text">{content}</p> : isGenerating && <IsTypingState />}
                </div>
            </div>
        </div>
    );
}
