// packages/sveltekit/src/lib/components/Header.svelte
<script lang="ts">
    import { createAgentAvatarUrl } from "@mecha-agent-inference-client/core/client";
    import { resetChatState } from "../store/chat.svelte.js";
    import SwitchTheme from "./SwitchTheme.svelte";

    const { agent }: { agent: Agent } = $props();
</script>

<div class="header">
    <div class="agent-info">
        {#if agent.avatar}
            <img
                class="avatar"
                src={createAgentAvatarUrl(agent.avatar)}
                alt="Agent Avatar"
            />
        {:else}
            <span class="avatar agent-fallback-avatar"></span>
        {/if}
        <div>
            <p class="agent-name">{agent.agentName}</p>
            <p class="agent-description">{agent.description}</p>
        </div>
    </div>
    <div class="actions">
        <SwitchTheme />
        <button class="new-chat-button" onclick={resetChatState}>
            New Chat
        </button>
    </div>
</div>

// packages/nextjs/src/components/Header.tsx
import Image from "next/image";
import { useContext } from "react";
import { chatContext } from "./ChatContextProvider";
import SwitchTheme from "./SwitchTheme";
import { createAgentAvatarUrl } from "@mecha-agent-inference-client/core/client";

export default function Header({ agent }: { agent: Agent }) {
    const state = useContext(chatContext)

    function startNewChat() {
        state.resetState()
    }

    return (
        <div className="header">
            <div className="agent-info">
                {
                    agent.avatar ?
                        <Image
                            width={48}
                            height={48}
                            className="avatar"
                            src={createAgentAvatarUrl(agent.avatar)}
                            alt="Agent Avatar"
                        /> : <span className="avatar agent-fallback-avatar" />
                }
                <div>
                    <p className="agent-name">{agent.agentName}</p>
                    <p className="agent-description">{agent.description}</p>
                </div>
            </div>
            <div className="actions">
                <SwitchTheme />
                <button
                    className="new-chat-button"
                    onClick={startNewChat}
                >
                    New Chat
                </button>
            </div>
        </div>
    )
};
