// packages/sveltekit/src/lib/components/LoadingAgent.svelte
<div class="loading-agent-container">
    <div class="loading-agent-bar pulse"></div>
    <div class="loading-agent-body">
        <div class="loading-agent-greeting-message pulse"></div>
        <div class="loading-agent-prompt-input pulse"></div>
    </div>
    <div class="loading-agent-bar pulse"></div>
</div>

// packages/nextjs/src/components/LoadingAgent.tsx
export default function LoadingAgent() {
    return (
        <div className="loading-agent-container">
            <div className="loading-agent-bar pulse">
            </div>
            <div className="loading-agent-body">
                <div className="loading-agent-greeting-message pulse">
                </div>
                <div className="loading-agent-prompt-input pulse">
                </div>
            </div>
            <div className="loading-agent-bar pulse">
            </div>
        </div>
    )
};
