// packages/sveltekit/src/lib/components/MechaAgentChat.svelte
<script lang="ts">
  import "@mecha_agent_inference_client/core/styles.css";
  import PromptInput from "./PromptInput.svelte";
  import Header from "./Header.svelte";
  import Footer from "./Footer.svelte";
  import ChatBody from "./ChatBody.svelte";
  import Alert from "./Alert.svelte";
  import LoadingAgent from "./LoadingAgent.svelte";
  import { onMount } from "svelte";
  import { agentState, fetchAgentData } from "../store/agent.svelte.js";
  import { chatState } from "../store/chat.svelte.js";
  import { defaultRouteHandlerPath } from "@mecha_agent_inference_client/core/client";

  const props: MechaAgentConfig = $props();

  const config = $state({
    ...props,
    routeHandlerPath: props.routeHandlerPath || defaultRouteHandlerPath,
  });

  function setTheme(idDarkTheme: boolean) {
    if (idDarkTheme) {
      document.querySelector("#mecha-agent-chat")?.classList.add("dark");
    } else {
      document.querySelector("#mecha-agent-chat")?.classList.remove("dark");
    }
  }

  onMount(() => {
    fetchAgentData(config);
    const theme = localStorage.getItem("mecha-agent-chat-theme");
    if (theme) {
      setTheme(theme === "dark");
    } else {
      const systemIsDark = window.matchMedia(
        "(prefers-color-scheme: dark)",
      ).matches;
      setTheme(systemIsDark);
    }

    chatState.chatId =
      localStorage.getItem("last-mecha-agent-chat-session") || "";
  });
</script>

<div id="mecha-agent-chat">
  {#if agentState.loading}
    <LoadingAgent />
  {:else if agentState.error}
    <Alert message={agentState.error} actionIcon={retryButton} />
  {:else if agentState.agent}
    <div class="chat-layout">
      <Header agent={agentState.agent} />
      <div class="chat-body-container">
        <ChatBody {config} agent={agentState.agent} />
        <PromptInput {config} />
      </div>
      <Footer />
    </div>
  {/if}
</div>

{#snippet retryButton()}
  <button onclick={() => fetchAgentData(config)}>Retry</button>
{/snippet}

// packages/nextjs/src/components/MechaAgentChat.tsx
"use client"
import "@mecha_agent_inference_client/core/styles.css"
import { useEffect } from "react"
import useAgent from "../hooks/useAgent"
import Alert from "./Alert"
import LoadingAgent from "./LoadingAgent"
import ChatLayout from "./ChatLayout"
import { defaultRouteHandlerPath } from "@mecha_agent_inference_client/core/client"

export default function MechaAgentChat(props: MechaAgentConfig) {
    const config = {
        ...props,
        routeHandlerPath: props.routeHandlerPath || defaultRouteHandlerPath,
    }

    const { agent, agentLoading, agentError, refetchAgent } = useAgent(config);

    function setTheme(idDarkTheme: boolean) {
        if (idDarkTheme) {
            document.querySelector("#mecha-agent-chat")?.classList.add('dark')
        } else {
            document.querySelector("#mecha-agent-chat")?.classList.remove('dark')
        }
    }

    useEffect(() => {
        const theme = localStorage.getItem("mecha-agent-chat-theme");
        if (theme) {
            setTheme(theme === "dark")
        } else {
            const systemIsDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
            setTheme(systemIsDark)
        }
    }, [])

    return (
        <div id="mecha-agent-chat">
            {
                agentLoading ? <LoadingAgent /> :
                    agentError ? <Alert
                        message={agentError}
                        actionIcon={<button onClick={refetchAgent}>Retry</button>}
                    /> :
                        agent ? <ChatLayout agent={agent} config={config} /> : null
            }
        </div>
    )
};
